# Cate Core:    2.0.0.dev2
# Cate Desktop: 2.0.0-dev.2, b6

language: node_js

node_js:
  - "8"

#env:
#  global:
#    - FTP_USER=ccitbx
#    - FTP_HOST=ftp.brockmann-consult.de
#     # using http://rkh.github.io/travis-encrypt/public/index.html
#     # FTP_PASSWORD
#     - secure: "z1JTkX8ULv09KNASimf6vlK4lV8BDAIKfuhOUm+PIhxOacFyVaHj3LArP7u0+qeqE3nUemRT6Xj8FJjD4PTBc98sgSk1RsJIBF5q7fKpAEwoUe2O/xGQKtdNxPsEGCn8SDy1AUP9UxRafhY8vAHUb7OtOuTH3t8YnFXe3BJq3CTckzegrTlRgn9pLGNkZZJ50n3Ao/zDCmm7BK5+U6g+QJMdRGfRBFvAbP5b6LgLO3Ep4AxFLmXg6a4NSuQWJj1r//+rFcyC/Y3k4koaRXUdyyvjKYQwB1Yg2zZCjbtOSsD1cxuxhDSBJ++nsq0EuJr6KSOvk599EnQVhZAUC8xBT7SgJuuSI7SKuJ+Ua/cuD4uGoB2UuoxoioufpjmxpAhmOzxrovjQjPG4odujtUcO0zUufpA5Vh9rqpWopdCTvrJiF+u/DgWAl/LSXWIT2O6YIxOMetligEfYD4/PO8vMbNHGxvpFx0QhmOcWs6ercY9yphx7d9kOBqCCoXTCDO8TbNDnyxXAxnuH4YQNKbqreM1/L0tnKSfkX8ovzvU9XKKDVMixt/kDI+UmPacsxj2HKGkKLeMsXZsmxauiGmeLOd99UoXXE/BkM5tTTxvjL1VuCpb6yJboxdwSyq/ZO85j1MIl9SrABNW/D2NV/v9uyCX9pTk57uYXAeduwVAsb4E="

os:
  - linux
  - osx

dist: trusty

addons:
  apt:
    packages:
    - icnsutils
    - xz-utils

cache:
  directories:
    - node_modules

install:
  #
  # cate installer
  #
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  #    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  #  else
  #    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #  fi
  #- bash miniconda.sh -b -p $HOME/miniconda
  #- export PATH="$HOME/miniconda/bin:$PATH"
  #- hash -r
  #- conda config --set always_yes yes --set changeps1 no
  #- conda update conda
  #- conda install -y constructor
  #- conda list
  #
  # cate-desktop installer
  #
  - git clone https://github.com/CCI-Tools/cate-desktop.git
  - (cd cate-desktop && npm install)

script:
  #- constructor installer
  - cd cate-desktop
  - npm run clean
  - npm run compile
  - npm run publish
  - cd ..

#after_success:
#  # only publish artifacts on master branch when pushed (not from cron or PRs)
#  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_EVENT_TYPE" = "push" ]; then
#      ./upload-to-ftp.sh;
#    fi
