# version here is only relevant for the AppVeyor CI, no need to adjust
version: '{build}'

build: off

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda36-x64"
  nodejs_version: "6.9.0"
  apiUrl : "https://ci.appveyor.com/api"

branches:
  only:
    - master

install:
  # core
  - set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda install -y constructor
  # desktop
  - git clone https://github.com/CCI-Tools/cate-desktop.git
  - cd cate-desktop
  - ps: Install-Product node $env:nodejs_version x64
  - npm install
  - cd ..

build_script:
  # core
  - constructor --verbose --debug  installer
  - ps: $MINICONDA_FILE="*.exe"
  # desktop
  - cd cate-desktop
  - npm run dist
  - cd ..
  - move cate-desktop\dist win64
  - ps: cp $MINICONDA_FILE win64

artifacts:
  - path: 'win64\*.exe'
    name: installer

deploy:
  - provider: FTP
    protocol: ftp
    host: ftp.brockmann-consult.de
    username: ccitbx
    password:
      secure: pgE0Tsk7QVyQ6jvH42jqWA==
    folder: software
    debug: true
