version: '0.7.0a4.{build}'

build: off

branches:
  only:
    - master

install:
  - set PATH=C:\Miniconda35-x64;C:\Miniconda35-x64\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda install -y constructor
  - git clone https://github.com/CCI-Tools/cate-desktop.git
  - cd cate-desktop
  - npm install
  - cd ..

build_script:
  - constructor installer
  - cd cate-desktop
  - npm run dist
  - cd ..

artifacts:
  - path: '*.exe'
    name: miniconda-exe

deploy:
  - provider: FTP
    protocol: ftp
    host: ftp.brockmann-consult.de
    username: ccitbx
    password:
      secure: pgE0Tsk7QVyQ6jvH42jqWA==
    artifact: miniconda-exe
    folder: software/win64
    debug: true