version: '0.7.0a4.{build}'

build: off

branches:
  only:
    - master

install:
  - set PATH=C:\Miniconda35-x64;C:\Miniconda35-x64\Scripts;%PATH%
  - conda install -y constructor
  - constructor installer


artifacts:
  - path: '*.exe'
    name: cate-installer-exe
