version: '0.7.0a4.{build}'

build: off

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda35-x64"
  nodejs_version: "6.9.0"
  apiUrl : "https://ci.appveyor.com/api"

branches:
  only:
    - master

install:
  # core
  - set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda install -y constructor
  # desktop
  - git clone https://github.com/CCI-Tools/cate-desktop.git
  - cd cate-desktop
  - ps: Install-Product node $env:nodejs_version x64
  - npm install
  - cd ..

build_script:
  # core
  - constructor installer
  # desktop
  - cd cate-desktop
  - npm run dist
  - cd ..

artifacts:
  - path: '*.exe'
    name: miniconda-exe
  - path: 'cate-desktop\dist\*.exe'
    name: electron-exe

deploy:
  - provider: FTP
    protocol: ftp
    host: ftp.brockmann-consult.de
    username: ccitbx
    password:
      secure: pgE0Tsk7QVyQ6jvH42jqWA==
    folder: software/win64
    debug: true